### ISSUE TITLE
Option to provide API token

### ISSUE THREAD

**Issue by Geolim4** [harshjv/github-repo-size#10]
Hello,

As the free access to the API is limited, you should offer a way to setup a token to the extension settings :)

**Comment by harshjv** [comment]
Thanks @Geolim4 for your suggestions.

I am also looking forward to this feature but currently, I am a little busy.

Does anyone want to take this up? This will also solve #2. :)

**Comment by Geolim4** [comment]
I am not a Chrome Extension Developper, i don't know well the ecosystem, so sorry i can't handle this :'(

**Comment by harshjv** [comment]
Feature added in 0348cc1deaa2ea0c7a3eb0843535a892beb3331d
