### ISSUE TITLE
Browsing back in history doubles output in stats bar

### ISSUE THREAD

**Issue by uschek** [harshjv/github-repo-size#12]
### Steps to reproduce

1. go to repository, e.g. [github-repo-size](https://github.com/harshjv/github-repo-size)
1. browse issues
1. go one step back in browser history

### Result

![image](https://cloud.githubusercontent.com/assets/2123235/19205083/7c43d984-8ce0-11e6-8971-b013dcdf046f.png)

### Possible fix

Check if `li` element exists before [inserting](https://github.com/harshjv/github-repo-size/blob/e2efd1a64e8e943f0fcf9d72bdb4cb688e0d354f/src/inject.js#L110).

**Comment by harshjv** [comment]
Thanks @uschek for reporting this. It is fixed now. :)
