### ISSUE TITLE
Navigating from another pane to the Code pane results in the repo size not appearing

### ISSUE THREAD

**Issue by davidsawyer** [harshjv/github-repo-size#13]
In the gif below, I:

1. load the page fresh
2. the repo size does appear
3. navigate to Issues
4. navigate back to Code
5. the repo size does NOT appear

Let me know if you'd like me to take a stab at fixing this.

![nov-07-2016 10-24-43](https://cloud.githubusercontent.com/assets/724087/20063295/a1b77926-a4d4-11e6-9c65-92603b16ba98.gif)

**Comment by harshjv** [comment]
@davidsawyer thanks for reporting this issue!

Yep, if you want then do take a shot at fixing it. After all, It is an open source software 🎉

**Comment by davidsawyer** [comment]
Ah, I'm dumb.

I had an outdated version of the extension on my machine. I updated, and that solved the problem!

**Comment by harshjv** [comment]
Haha, cool! 👍🏻
