### ISSUE TITLE
How to see private repo size?

### ISSUE THREAD

**Issue by warmwhisky** [harshjv/github-repo-size#15]
I can see this in the docs "Generate a Github personal access token from here and click on extension icon to add it." But, could you elaborate?

**Comment by harshjv** [comment]
@warmwhisky done. see updated README.md

**Comment by saad749** [comment]
Does it still work? I am unable to use it with the mentioned method

**Comment by ADTC** [comment]
I think it's missing a crucial step regarding the token's scope. See my issue #24
