### ISSUE TITLE
Is activeTab permission necessary?

### ISSUE THREAD

**Issue by frangio** [harshjv/github-repo-size#16]
I've seen the documentation at https://developer.chrome.com/extensions/activeTab, but I can't figure out why this permission would be necessary.

**Comment by KIPdeKIP** [comment]
From https://github.com/harshjv/github-repo-size/pull/17#issuecomment-279042619 :

> Actually, I was experimenting with `tabs.executeScript` but I ended up using `prompt` in background script and removed `tabs.executeScript`, but forgot to remove `activeTab` permission.

It's not necessary.
