### ISSUE TITLE
Exception when there is a git submodule in the repo

### ISSUE THREAD

**Issue by Senorsen** [harshjv/github-repo-size#18]
```
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
at chrome-extension://apnjnioapinblneaedefcnopcjepgkci/src/inject.js:154:46
```
![image](https://cloud.githubusercontent.com/assets/4176091/23350119/3aad0936-fcf3-11e6-8556-90cd32faed83.png)
![image](https://cloud.githubusercontent.com/assets/4176091/23350144/78552fca-fcf3-11e6-8756-2386ba685495.png)

It is a private repo, thus no more details can I tell, thanks.

**Comment by harshjv** [comment]
Fixed in v0.3.1
