### ISSUE TITLE
The extension is disabled due to a permission change. Need explanation

### ISSUE THREAD

**Issue by AnwarShah** [harshjv/github-repo-size#28]
The new permission has disabled this extension on my chrome. I wanted to know the reason and impact of this permission change.

It says
` Read and change your data on api.github.com and github.com`

Thank you for this helpful extension

**Comment by harshjv** [comment]
@AnwarShah Thanks for your query! `api.github.com`isn't required. It has been removed in `0.4.1`.

**Comment by harshjv** [comment]
@AnwarShah `github.com` is required because this extension `injects` a code snippet to display size information on `github.com` pages.

**Comment by AnwarShah** [comment]
That's quick. Thank you.
