### ISSUE TITLE
File and Folder sizes

### ISSUE THREAD

**Issue by manparvesh** [harshjv/github-repo-size#3]
Will it be possible to display individual file and folder sizes as well?

**Comment by harshjv** [comment]
Ya, this is possible with GitHub API. This feature is already a WIP :)

If you want to know more about this, visit https://developer.github.com/v3/git/trees

**Comment by harshjv** [comment]
See https://github.com/harshjv/github-repo-size/commit/961717e666d57589a37592ef458657de0fdb3a55

**Comment by manparvesh** [comment]
Looks good, @harshjv! :smile:

**Comment by myfairsyer** [comment]
What about folder size? :)
