### ISSUE TITLE
Wrong repo size

### ISSUE THREAD

**Issue by flawyte** [harshjv/github-repo-size#33]
In addition to #31, I've noticed too that sometimes the repo size is completely wrong, either too big or too small.

# Example
- Go to this repo : https://github.com/bitoiu/markwrap
- As time of writing, the total size displayed is **4.28MB**
- Click on the `assets` folder
- Notice that the size of the `example.gif` file only is **4.58MB**

**Comment by Yousefjb** [comment]
I don't want to create another issue so here is another example of wrong size

[https://github.com/Yousefjb/TravianTactics](https://github.com/Yousefjb/TravianTactics)

size displayed: 172 KB
actual size: 1.17 MB

there is two files only: 
- README.md [125B]
- script.js [1.17MB]

**Comment by grenudi** [comment]
Same
repo https://github.com/grenudi-js-modules/testing 
api https://api.github.com/repos/grenudi-js-modules/testing
size always shows 3 , what ever I do , it always show 3

![image](https://user-images.githubusercontent.com/17498075/57296422-a465f100-70d5-11e9-8f2c-ed5f34c71e6a.png)
![image](https://user-images.githubusercontent.com/17498075/57296453-b6479400-70d5-11e9-85c8-73e119882c09.png)

**Comment by grenudi** [comment]
> Same
> repo https://github.com/grenudi-js-modules/testing
> api https://api.github.com/repos/grenudi-js-modules/testing
> size always shows 3 , what ever I do , it always show 3
> 
> ![image](https://user-images.githubusercontent.com/17498075/57296422-a465f100-70d5-11e9-8f2c-ed5f34c71e6a.png)
> ![image](https://user-images.githubusercontent.com/17498075/57296453-b6479400-70d5-11e9-85c8-73e119882c09.png)

never mind, it updated after 20 min, and seems to work as supposed

**Comment by harshjv** [comment]
See https://github.com/harshjv/github-repo-size/issues/9#issuecomment-239745588
