### ISSUE TITLE
Hover mouse on repo size icon shows null tooltip

### ISSUE THREAD

**Issue by picolino** [harshjv/github-repo-size#41]
Reproduce steps:
1. Click on repo size icon to load folders size
2. Hover mouse on it
3. Tooltip "null" shown

See image:
![image](https://user-images.githubusercontent.com/17460456/68941374-c0e69280-07b6-11ea-94c3-2d52aca027ae.png)

Just my 2 cents 🙂

**Comment by msvamp** [comment]
This was fixed in https://github.com/harshjv/github-repo-size/commit/72041e354a2cf4d60f2a50b5791d3857558305e6
Please close this issue 🙃

**Comment by picolino** [comment]
Yep, fixed
