### ISSUE TITLE
[ASK FOE HELP! ] About setting the repositoty size

### ISSUE THREAD

**Issue by inexcel** [harshjv/github-repo-size#44]
Hi，Harsh ！
Thanks for your contributions，i have succeeded in setting "viewing size of private repositories". Just like the below pic shows, the size of each files have been shown. 
![image](https://user-images.githubusercontent.com/57343270/76390183-e4f26300-63a7-11ea-9346-eef47fbd455c.png)
You have writen as the follows:
> **Temporarily override then token**
> You can set `x-github-token` in `localStorage` to your access token, and the extension will use this value even if you've previously set token.[https://github.com/harshjv/github-repo-size#private-repository/](url)

However, i can't find the right way to set just like the below pic. 
![image](https://user-images.githubusercontent.com/57343270/76390712-dc4e5c80-63a8-11ea-9882-3adae69c769e.png)

CAN YOU HELP ME PLEASE? i am new to github.

- Do i need to dowload some softwares or add new files of some types to `repo`？

- Where can i find the  `x-github-token` in `localStorage` just like you said?

**Comment by yinjunjie98** [comment]
LOL!  
IT WORKS!!! 
THANKS !
