### ISSUE TITLE
when I use push -f to update my repos but repo size not change

### ISSUE THREAD

**Issue by xiantang** [harshjv/github-repo-size#47]
![image](https://user-images.githubusercontent.com/34479567/77923240-bd225b00-72d4-11ea-9231-9269e8d627f6.png)
this is my repos size which is `github-repo-size` gain.
but i use push -f to reduce my repo size.
now my repo size is 
![image](https://user-images.githubusercontent.com/34479567/77923355-efcc5380-72d4-11ea-8177-1d93986ab44d.png)
i think is some wrong.

**Comment by xiantang** [comment]
![image](https://user-images.githubusercontent.com/34479567/77923550-2e620e00-72d5-11ea-8773-8f0afaa0d9c5.png)
![image](https://user-images.githubusercontent.com/34479567/77923583-36ba4900-72d5-11ea-8c47-8870d597157b.png)
you can easily see not have such file bigger than 100MB

**Comment by xiantang** [comment]
my repo link is. https://github.com/xiantang/Spider

**Comment by msvamp** [comment]
This was already reported before and it's a problem at GitHub's end
See https://github.com/harshjv/github-repo-size/issues/9#issuecomment-239745588

> However, due to the way we store repositories, the size may be way off for large repositories and repositories with a lot of forks (i.e. large networks). **Also, the size might not be refreshed immediately.**
