### ISSUE TITLE
Support new repository page

### ISSUE THREAD

**Issue by guidezpl** [harshjv/github-repo-size#50]
Github is previewing a new look for the repository page (enable it by going to Avatar  → feature preview  → Repository Refresh), which isn't compatible with the extension.

<img width="1655" alt="Screen Shot 2020-06-18 at 1 15 35 AM" src="https://user-images.githubusercontent.com/6655696/84960172-3f1a6700-b101-11ea-850d-6b3554893558.png">

**Comment by harshjv** [comment]
Thanks for bringing this up. I am working on a PR to address this issue.

**Comment by harshjv** [comment]
Support for new Github UI is shipped in version 0.6.0.

**Comment by mrctrl69** [comment]
When it's rooling out?

**Comment by harshjv** [comment]
It's currently pending review by Chrome. I hope it to be out in 24-72 hours.

**Comment by mrctrl69** [comment]
Surely can't wait hahaha

**Comment by harshjv** [comment]
Keeping this issue open until the new version is reviewed and published on chrome web store.

**Comment by mikhaelkh** [comment]
New placement of repo size is bad. It is among the clickable items which are visible everywhere in the repo while repo size is visible only on the main repo page. Better move it:
![repo-size](https://user-images.githubusercontent.com/8005688/85923220-fd708580-b891-11ea-8cf8-a60531139171.png)

**Comment by guidezpl** [comment]
Moving it to both places would cover all cases and makes more sense IMO

**Comment by harshjv** [comment]
The displayed repo size is actually a clickable element. When you click on it, it loads directory sizes. :)

**Comment by guidezpl** [comment]
Right, I think they just meant the placement makes more sense to be displayed along with commit, branch, and tag information, rather than looking like a tab

**Comment by harshjv** [comment]
Oh, I see. Sure, let's do it. @guidezpl do you want to take a stab at this?

**Comment by harshjv** [comment]
New version is published on Chrome Web Store on June 26, 2020. Tracking position related changes in #60
