### ISSUE TITLE
Wrong size ?

### ISSUE THREAD

**Issue by Geolim4** [harshjv/github-repo-size#9]
Hi,

I just find out that the provided size is wrong oO
Let's try with PhpFastCache:
https://api.github.com/repos/PHPSocialNetwork/phpfastcache

The size is **19153** which mean **18,7Ko(KiloOctet/KiloBytes)** which mean ~ **0,02Mo (MegaOctet/MegaBytes)**

However your extension, displays 18.7 MB, i guess Megabytes (because the B is uppercase).
So there's something wrong in the math.

I had a look at the code and found out this in inject.js line 20:
`bytes *= 1024`

It confuses me a lot. Are you calculating per-bits-based or  per-bytes-based ?

Cheers,
Georges

**Comment by harshjv** [comment]
The size returned by GitHub API is in KB.
So 19,153 KB is ~18.7 MB.

For more details, see this SO thread: http://stackoverflow.com/a/8679592/1924979

**Comment by Geolim4** [comment]
ok thanks you for the link :)

**Comment by harshjv** [comment]
I guess, there is some inconsistency with repo size and file size returned from GitHub API.

Repo size in `/:user/:repo` is calculated differently than `/:user/:repo/contents/:filePath`.

**Comment by harshjv** [comment]
See https://github.com/harshjv/github-repo-size/commit/0415a4e185b5095fa85afcb3be058b325aa50165

**Comment by harshjv** [comment]
From GitHub Support;

> Hi Harsh,
> 
> The size attribute represents disk usage in KB, and is what is listed when viewing the sizes of your personal repositories:
> 
> https://github.com/settings/repositories
> 
> However, due to the way we store repositories, the size may be way off for large repositories and repositories with a lot of forks (i.e. large networks). Also, the size might not be refreshed immediately. We might be removing this attributes soon from API responses since there is no simple fix and it creates more confusion than value. I recommend that you don't rely on this value and that you compute the size of the repository yourself.
> 
> I hope this answers your question.
> 
> Best,
> Ivan

Now, looking for a workaround.

**Comment by harshjv** [comment]
Also, have to revert https://github.com/harshjv/github-repo-size/commit/0415a4e185b5095fa85afcb3be058b325aa50165

**Comment by harshjv** [comment]
And, the `size` returned from `/:user/:repo/:contents/:filePath` is in **bytes**

**Comment by Geolim4** [comment]
Thanks you for your investigation !
